Flownative:
  Sentry:
    dsn: "%env:SENTRY_DSN%"
    environment: "%env:SENTRY_ENVIRONMENT%"
    release: "%env:SENTRY_RELEASE%"
    sampleRate: "%env:SENTRY_SAMPLE_RATE%"
    capture:
      excludeExceptionTypes: []

Neos:
  Flow:
    log:
      systemLogger:
        backend: Flownative\Sentry\Log\SentryFileBackend
